name: run GeckoAPI.py

on: 
    schedule:
        - cron: '*/30 * * * *'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
    
        - name: checkout repo content
          uses: actions/checkout@v2 # checkout the repository content to github runner
    
        - name: setup python
          uses: actions/setup-python@v4
          with:
            python-version: '3.9' # install the python version needed
            
        - name: install python packages
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            
        - name: execute py script # run main.py
          env:
            GECKO_KEY: ${{ secrets.GECKO_KEY }}
            TWILIO_ACC_SID: ${{ secrets.TWILIO_ACC_SID }}
            TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          run: python CoinTracker.py
               python GeckoAPI.py
        - name: commit files
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add -A
            git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
            
        - name: push changes
          uses: ad-m/github-push-action@v0.6.0
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main 